##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira - 9/11/2011                 ##
## GAPH/FACIN/PUCRS                                         ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Load the required standard cell libraries              ##
##  -Load synthesized netlist                               ##
##  -Load design constraints                                ##
##  -Generate a floorplan                                   ##
##############################################################
##Loading std cell libs / netlist / constraints / setting vdd/gnd
loadConfig layout/Mult_CSAdder.conf 0
setUIVar rda_Input ui_gndnet gnd
setUIVar rda_Input ui_pwrnet vdd
commitConfig
##Generating square floorplan (1) with 80% of density (0.8) with 3um margins (3 3 3 3)
floorPlan -site CORE -r 1 0.8 3 3 3 3
##fit screen
fit
