--------------------------------------------------------------
--               Simple Multiplier testbench                --
-- Script Generated for Undergrad class of microelectronics --
-- Generated by Fernando Moraes                             --
-- GAPH/FACIN/PUCRS                                         --
--------------------------------------------------------------
library ieee,work;
use ieee.std_logic_unsigned.all;
use ieee.std_logic_1164.all;


entity testa_mult is
end entity testa_mult;


architecture testa_mult of testa_mult is 

        signal a    : std_logic_vector(3 downto 0);
        signal b    : std_logic_vector(3 downto 0);
        signal prod : std_logic_vector(7 downto 0);
        signal cout : std_logic;

begin

        multiplicador:  entity work.Mult_CSAdder port map( a, b, prod);

        a   <= x"2" after 0   ns,               
               x"8" after 100 ns, 
               x"5" after 200 ns, 
               x"1" after 300 ns, 
               x"F" after 400 ns, 
               x"0" after 500 ns, 
               x"F" after 600 ns,
			   x"0" after 1000 ns; 

        b   <= x"3" after 0   ns,   
               x"B" after 100 ns, 
               x"4" after 200 ns,  
               x"1" after 300 ns,  
               x"2" after 400 ns,  
               x"0" after 500 ns, 
               x"F" after 600 ns,
			   x"0" after 1000 ns;  

			   

end architecture testa_mult;
